# Generated by Django 5.1.7 on 2025-03-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('TarefaID', models.AutoField(primary_key=True, serialize=False)),
                ('Descricao', models.CharField(max_length=255)),
                ('Status', models.CharField(max_length=50)),
                ('DataCriacao', models.DateTimeField(auto_now_add=True)),
                ('DataConclusao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
