# Generated by Django 5.0.13 on 2025-03-20 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='DataConclusao',
            new_name='data_conclusao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='DataCriacao',
            new_name='data_criacao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='Descricao',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='Status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='tarefa',
            old_name='TarefaID',
            new_name='tarefa_id',
        ),
    ]
