# Generated by Django 5.0.13 on 2025-03-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_rename_dataconclusao_tarefa_data_conclusao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('concluída', 'Concluída')], default='pendente', max_length=50),
        ),
    ]
